   
# if db(db.func).isempty():
    # db.func.insert(func_code = 'dashboard', func_name = 'Dashboard', parent_code = '')
    # db.func.insert(func_code = 'map', func_name = 'Map', parent_code = '')
    # db.func.insert(func_code = 'realtime', func_name = 'Realtime', parent_code = '')
    # db.func.insert(func_code = 'camera', func_name = 'Camera', parent_code = '')
    # db.func.insert(func_code = 'aqi', func_name = 'AQI', parent_code = '')
    # db.func.insert(func_code = 'wqi', func_name = 'WQI', parent_code = '')
    # db.func.insert(func_code = 'notifications', func_name = 'Notifications', parent_code = '')
    # db.func.insert(func_code = 'alarm_log', func_name = 'Alarm logs', parent_code = '')
    # db.func.insert(func_code = 'station_off_log', func_name = 'View station disconnect logs', parent_code = '')
    # db.func.insert(func_code = 'data_alarm', func_name = 'Data alarm', parent_code = '')
    # db.func.insert(func_code = 'data_adjust', func_name="Data adjust", parent_code='')
    # db.func.insert(func_code = 'data', func_name = 'Manage data', parent_code = '')
    # db.func.insert(func_code = 'adjust_schedule', func_name = 'Manage adjustment schedules', parent_code = '')
    # db.func.insert(func_code = 'commands', func_name = 'Manage commands', parent_code = '')
    # db.func.insert(func_code = 'command_results', func_name = 'Manage command results', parent_code = '')
    # db.func.insert(func_code = 'commands_schedule', func_name = 'Make command schedules', parent_code = '')
    # db.func.insert(func_code = 'ftp_transfer', func_name = 'File transfer', parent_code = '')
    # db.func.insert(func_code = 'settings', func_name = 'Settings', parent_code = '')
    # db.func.insert(func_code = 'command_log', func_name = 'Command log', parent_code = '')

    # db.func.insert(func_code = 'admin_batch', func_name = 'Manage batch background', parent_code = '')
    # db.func.insert(func_code = 'admin_func', func_name = 'System functions', parent_code = '')
    # db.func.insert(func_code = 'admin_user', func_name = 'Admin users', parent_code = '')
    # db.func.insert(func_code='admin_group', func_name='Admin groups', parent_code='')
    # db.func.insert(func_code='admin_grant_privilege', func_name='Grant privileges', parent_code='')
    # db.func.insert(func_code='admin_reset_pwd', func_name="Reset user's password", parent_code='')

    # db.func.insert(func_code='master_province', func_name="Master provinces", parent_code='')
    # db.func.insert(func_code='master_area', func_name="Master areas", parent_code='')
    # db.func.insert(func_code='master_station_type', func_name="Master station types", parent_code='')
    # db.func.insert(func_code='master_indicator', func_name="Master indicators", parent_code='')
    # db.func.insert(func_code='master_station', func_name="Master stations", parent_code='')
    # db.func.insert(func_code='master_equipment', func_name="Master equipments", parent_code='')
    # db.func.insert(func_code='master_qcvn', func_name="Master qcvns", parent_code='')
    # db.func.insert(func_code='master_agent', func_name="Master agents", parent_code='')